name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: purcell/setup-emacs@master
        with:
          version: '24.3'
      - uses: conao3/setup-cask@master

      - name: Run tests
        run: |
          cask install
          cask exec ert-runner
